version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: babel-preset-gatsby-package
    versions:
    - 0.11.0
    - 0.12.0
    - 1.0.0
    - 1.1.0
    - 1.2.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
